package com.popcorn.utils.enums;

public enum BoundNodeKind {

    OBJECT_STATEMENT,

    LITERAL_EXPRESSION,
    UNARY_EXPRESSION,
    BINARY_EXPRESSION,
    ASSIGNMENT_EXPRESSION,
    NAME_EXPRESSION,
    IF_STATEMENT,
    ELSE_IF_STATEMENT,
    ELSE_STATEMENT,
    PRINT_STATEMENT,

    SKIP

}
