package com.popcorn.utils.enums;

public enum BoundNodeKind {

    LITERAL_EXPRESSION,
    UNARY_EXPRESSION,
    BINARY_EXPRESSION,
    VARIABLE_EXPRESSION,
    ASSIGNMENT_EXPRESSION,
    NAME_EXPRESSION,
    NULL_EXPRESSION

}
